version: "2"
services:
  player-nikhil:
    build: './players'
    ports:
      - 8081:8081
    environment:
      EXPRESS_PORT: 8081
      PLAYER_NAME: 'Nikhil'
      DEFENCE_ARRAY_LENGTH: 8
  player-mihir:
    build: './players'
    ports:
      - 8082:8082
    environment:
      EXPRESS_PORT: 8082
      PLAYER_NAME: 'Mihir'
      DEFENCE_ARRAY_LENGTH: 8
  player-amit:
    build: './players'
    ports:
      - 8083:8083
    environment:
      EXPRESS_PORT: 8083
      PLAYER_NAME: 'Amit'
      DEFENCE_ARRAY_LENGTH: 7
  player-joey:
    build: './players'
    ports:
      - 8084:8084
    environment:
      EXPRESS_PORT: 8084
      PLAYER_NAME: 'Joey'
      DEFENCE_ARRAY_LENGTH: 7
  player-chandler:
    build: './players'
    ports:
      - 8085:8085
    environment:
      EXPRESS_PORT: 8085
      PLAYER_NAME: 'Chandler'
      DEFENCE_ARRAY_LENGTH: 6
  player-vivek:
    build: './players'
    ports:
      - 8086:8086
    environment:
      EXPRESS_PORT: 8086
      PLAYER_NAME: 'Vivek'
      DEFENCE_ARRAY_LENGTH: 6
  player-russel:
    build: './players'
    ports:
      - 8087:8087
    environment:
      EXPRESS_PORT: 8087
      PLAYER_NAME: 'Russel'
      DEFENCE_ARRAY_LENGTH: 5
  player-pritam:
    build: './players'
    ports:
      - 8088:8088
    environment:
      EXPRESS_PORT: 8088
      PLAYER_NAME: 'Pritam'
      DEFENCE_ARRAY_LENGTH: 5
